-- ==========================================================
-- SQL Migration: Unique Student Names per Course
-- ==========================================================

UPDATE online_comments SET user_id = 7, comment_author = 'brijesh' WHERE comment_ID = 8;
UPDATE online_comments SET user_id = 365, comment_author = 'brijesh' WHERE comment_ID = 21;
UPDATE online_users SET display_name = 'Brijesh Desai' WHERE ID = 365;
UPDATE online_comments SET user_id = 377, comment_author = 'socialvipulchudasamacom' WHERE comment_ID = 24;
UPDATE online_users SET display_name = 'VC Social' WHERE ID = 377;
UPDATE online_comments SET user_id = 418, comment_author = 'Ananya Sharma' WHERE comment_ID = 71;
UPDATE online_users SET display_name = 'Ananya Sharma' WHERE ID = 418;
UPDATE online_comments SET user_id = 419, comment_author = 'Rohit Verma' WHERE comment_ID = 72;
UPDATE online_users SET display_name = 'Rohit Verma' WHERE ID = 419;
UPDATE online_comments SET user_id = 420, comment_author = 'Priya Patel' WHERE comment_ID = 73;
UPDATE online_users SET display_name = 'Priya Patel' WHERE ID = 420;
UPDATE online_comments SET user_id = 421, comment_author = 'Rohan Kapoor' WHERE comment_ID = 74;
UPDATE online_users SET display_name = 'Rohan Kapoor' WHERE ID = 421;
UPDATE online_comments SET user_id = 422, comment_author = 'Sneha Joshi' WHERE comment_ID = 75;
UPDATE online_users SET display_name = 'Sneha Joshi' WHERE ID = 422;
UPDATE online_comments SET user_id = 423, comment_author = 'Kunal Malhotra' WHERE comment_ID = 76;
UPDATE online_users SET display_name = 'Kunal Malhotra' WHERE ID = 423;
UPDATE online_comments SET user_id = 424, comment_author = 'Ritu Deshmukh' WHERE comment_ID = 77;
UPDATE online_users SET display_name = 'Ritu Deshmukh' WHERE ID = 424;
UPDATE online_comments SET user_id = 425, comment_author = 'Aditya Singhania' WHERE comment_ID = 78;
UPDATE online_users SET display_name = 'Aditya Singhania' WHERE ID = 425;
UPDATE online_comments SET user_id = 426, comment_author = 'Tanvi Nair' WHERE comment_ID = 79;
UPDATE online_users SET display_name = 'Tanvi Nair' WHERE ID = 426;
UPDATE online_comments SET user_id = 427, comment_author = 'Vikram Chopra' WHERE comment_ID = 80;
UPDATE online_users SET display_name = 'Vikram Chopra' WHERE ID = 427;
UPDATE online_comments SET user_id = 431, comment_author = 'Divya Iyer' WHERE comment_ID = 171;
UPDATE online_users SET display_name = 'Divya Iyer' WHERE ID = 431;
UPDATE online_comments SET user_id = 432, comment_author = 'Amit Sen' WHERE comment_ID = 172;
UPDATE online_users SET display_name = 'Amit Sen' WHERE ID = 432;
UPDATE online_comments SET user_id = 433, comment_author = 'Neha Bansal' WHERE comment_ID = 173;
UPDATE online_users SET display_name = 'Neha Bansal' WHERE ID = 433;
UPDATE online_comments SET user_id = 434, comment_author = 'Karan Mehra' WHERE comment_ID = 174;
UPDATE online_users SET display_name = 'Karan Mehra' WHERE ID = 434;
UPDATE online_comments SET user_id = 435, comment_author = 'Pooja Rao' WHERE comment_ID = 175;
UPDATE online_users SET display_name = 'Pooja Rao' WHERE ID = 435;
UPDATE online_comments SET user_id = 436, comment_author = 'Shreya Roy' WHERE comment_ID = 176;
UPDATE online_users SET display_name = 'Shreya Roy' WHERE ID = 436;
UPDATE online_comments SET user_id = 437, comment_author = 'Varun Mehta' WHERE comment_ID = 177;
UPDATE online_users SET display_name = 'Varun Mehta' WHERE ID = 437;
UPDATE online_comments SET user_id = 438, comment_author = 'Simran Kaur' WHERE comment_ID = 178;
UPDATE online_users SET display_name = 'Simran Kaur' WHERE ID = 438;
UPDATE online_comments SET user_id = 439, comment_author = 'Nikhil Bhatt' WHERE comment_ID = 179;
UPDATE online_users SET display_name = 'Nikhil Bhatt' WHERE ID = 439;
UPDATE online_comments SET user_id = 440, comment_author = 'Ishita Jain' WHERE comment_ID = 180;
UPDATE online_users SET display_name = 'Ishita Jain' WHERE ID = 440;
UPDATE online_comments SET user_id = 441, comment_author = 'Harish Pillai' WHERE comment_ID = 181;
UPDATE online_users SET display_name = 'Harish Pillai' WHERE ID = 441;
UPDATE online_comments SET user_id = 442, comment_author = 'Meera Nambiar' WHERE comment_ID = 182;
UPDATE online_users SET display_name = 'Meera Nambiar' WHERE ID = 442;
UPDATE online_comments SET user_id = 443, comment_author = 'Gaurav Sethi' WHERE comment_ID = 183;
UPDATE online_users SET display_name = 'Gaurav Sethi' WHERE ID = 443;
UPDATE online_comments SET user_id = 444, comment_author = 'Kavya Kulkarni' WHERE comment_ID = 184;
UPDATE online_users SET display_name = 'Kavya Kulkarni' WHERE ID = 444;
UPDATE online_comments SET user_id = 445, comment_author = 'Rahul Sengupta' WHERE comment_ID = 185;
UPDATE online_users SET display_name = 'Rahul Sengupta' WHERE ID = 445;
UPDATE online_comments SET user_id = 446, comment_author = 'Anjali Menon' WHERE comment_ID = 186;
UPDATE online_users SET display_name = 'Anjali Menon' WHERE ID = 446;
UPDATE online_comments SET user_id = 447, comment_author = 'Manish Tiwari' WHERE comment_ID = 187;
UPDATE online_users SET display_name = 'Manish Tiwari' WHERE ID = 447;
UPDATE online_comments SET user_id = 448, comment_author = 'Pallavi Joshi' WHERE comment_ID = 188;
UPDATE online_users SET display_name = 'Pallavi Joshi' WHERE ID = 448;
UPDATE online_comments SET user_id = 449, comment_author = 'Siddharth Das' WHERE comment_ID = 189;
UPDATE online_users SET display_name = 'Siddharth Das' WHERE ID = 449;
UPDATE online_comments SET user_id = 450, comment_author = 'Natasha Bhatia' WHERE comment_ID = 190;
UPDATE online_users SET display_name = 'Natasha Bhatia' WHERE ID = 450;
UPDATE online_comments SET user_id = 4, comment_author = 'hardik3253' WHERE comment_ID = 14;
UPDATE online_comments SET user_id = 377, comment_author = 'socialvipulchudasamacom' WHERE comment_ID = 25;
UPDATE online_users SET display_name = 'VC Social' WHERE ID = 377;
UPDATE online_comments SET user_id = 1080, comment_author = 'Arpita Ganguly' WHERE comment_ID = 81;
UPDATE online_users SET display_name = 'Arpita Ganguly' WHERE ID = 1080;
UPDATE online_comments SET user_id = 1081, comment_author = 'Devashish Roy' WHERE comment_ID = 82;
UPDATE online_users SET display_name = 'Devashish Roy' WHERE ID = 1081;
UPDATE online_comments SET user_id = 1082, comment_author = 'Monali Thakur' WHERE comment_ID = 83;
UPDATE online_users SET display_name = 'Monali Thakur' WHERE ID = 1082;
UPDATE online_comments SET user_id = 1083, comment_author = 'Bhavesh Parekh' WHERE comment_ID = 84;
UPDATE online_users SET display_name = 'Bhavesh Parekh' WHERE ID = 1083;
UPDATE online_comments SET user_id = 1084, comment_author = 'Shruti Mahajan' WHERE comment_ID = 85;
UPDATE online_users SET display_name = 'Shruti Mahajan' WHERE ID = 1084;
UPDATE online_comments SET user_id = 1085, comment_author = 'Pranay Waghela' WHERE comment_ID = 86;
UPDATE online_users SET display_name = 'Pranay Waghela' WHERE ID = 1085;
UPDATE online_comments SET user_id = 1086, comment_author = 'Archana Soman' WHERE comment_ID = 87;
UPDATE online_users SET display_name = 'Archana Soman' WHERE ID = 1086;
UPDATE online_comments SET user_id = 1087, comment_author = 'Jatin Solanki' WHERE comment_ID = 88;
UPDATE online_users SET display_name = 'Jatin Solanki' WHERE ID = 1087;
UPDATE online_comments SET user_id = 1088, comment_author = 'Payal Somaiya' WHERE comment_ID = 89;
UPDATE online_users SET display_name = 'Payal Somaiya' WHERE ID = 1088;
UPDATE online_comments SET user_id = 1089, comment_author = 'Omkar Shinde' WHERE comment_ID = 90;
UPDATE online_users SET display_name = 'Omkar Shinde' WHERE ID = 1089;
UPDATE online_comments SET user_id = 1090, comment_author = 'Madhuri Bhave' WHERE comment_ID = 191;
UPDATE online_users SET display_name = 'Madhuri Bhave' WHERE ID = 1090;
UPDATE online_comments SET user_id = 1091, comment_author = 'Alok Srivastav' WHERE comment_ID = 192;
UPDATE online_users SET display_name = 'Alok Srivastav' WHERE ID = 1091;
UPDATE online_comments SET user_id = 1092, comment_author = 'Rashmi Varma' WHERE comment_ID = 193;
UPDATE online_users SET display_name = 'Rashmi Varma' WHERE ID = 1092;
UPDATE online_comments SET user_id = 1093, comment_author = 'Tushar Sawant' WHERE comment_ID = 194;
UPDATE online_users SET display_name = 'Tushar Sawant' WHERE ID = 1093;
UPDATE online_comments SET user_id = 1094, comment_author = 'Chetna Mistry' WHERE comment_ID = 195;
UPDATE online_users SET display_name = 'Chetna Mistry' WHERE ID = 1094;
UPDATE online_comments SET user_id = 1095, comment_author = 'Darshan Raval' WHERE comment_ID = 196;
UPDATE online_users SET display_name = 'Darshan Raval' WHERE ID = 1095;
UPDATE online_comments SET user_id = 1096, comment_author = 'Preeti Shenoy' WHERE comment_ID = 197;
UPDATE online_users SET display_name = 'Preeti Shenoy' WHERE ID = 1096;
UPDATE online_comments SET user_id = 1097, comment_author = 'Yogesh Gaikwad' WHERE comment_ID = 198;
UPDATE online_users SET display_name = 'Yogesh Gaikwad' WHERE ID = 1097;
UPDATE online_comments SET user_id = 1098, comment_author = 'Shweta Salve' WHERE comment_ID = 199;
UPDATE online_users SET display_name = 'Shweta Salve' WHERE ID = 1098;
UPDATE online_comments SET user_id = 1099, comment_author = 'Nitin Gadge' WHERE comment_ID = 200;
UPDATE online_users SET display_name = 'Nitin Gadge' WHERE ID = 1099;
UPDATE online_comments SET user_id = 1100, comment_author = 'Charu Sharma' WHERE comment_ID = 201;
UPDATE online_users SET display_name = 'Charu Sharma' WHERE ID = 1100;
UPDATE online_comments SET user_id = 1101, comment_author = 'Anandita Bose' WHERE comment_ID = 202;
UPDATE online_users SET display_name = 'Anandita Bose' WHERE ID = 1101;
UPDATE online_comments SET user_id = 1102, comment_author = 'Nilesh Chokshi' WHERE comment_ID = 203;
UPDATE online_users SET display_name = 'Nilesh Chokshi' WHERE ID = 1102;
UPDATE online_comments SET user_id = 1103, comment_author = 'Rupal Shah' WHERE comment_ID = 204;
UPDATE online_users SET display_name = 'Rupal Shah' WHERE ID = 1103;
UPDATE online_comments SET user_id = 1104, comment_author = 'Sameer Nadkarni' WHERE comment_ID = 205;
UPDATE online_users SET display_name = 'Sameer Nadkarni' WHERE ID = 1104;
UPDATE online_comments SET user_id = 1105, comment_author = 'Vandana Pathak' WHERE comment_ID = 206;
UPDATE online_users SET display_name = 'Vandana Pathak' WHERE ID = 1105;
UPDATE online_comments SET user_id = 1106, comment_author = 'Milind Dandekar' WHERE comment_ID = 207;
UPDATE online_users SET display_name = 'Milind Dandekar' WHERE ID = 1106;
UPDATE online_comments SET user_id = 1107, comment_author = 'Tanuja Jadhav' WHERE comment_ID = 208;
UPDATE online_users SET display_name = 'Tanuja Jadhav' WHERE ID = 1107;
UPDATE online_comments SET user_id = 1108, comment_author = 'Ashish Kakkad' WHERE comment_ID = 209;
UPDATE online_users SET display_name = 'Ashish Kakkad' WHERE ID = 1108;
UPDATE online_comments SET user_id = 1109, comment_author = 'Hiral Trivedi' WHERE comment_ID = 210;
UPDATE online_users SET display_name = 'Hiral Trivedi' WHERE ID = 1109;
UPDATE online_comments SET user_id = 4, comment_author = 'hardik3253' WHERE comment_ID = 12;
UPDATE online_comments SET user_id = 10, comment_author = 'hardik123' WHERE comment_ID = 19;
UPDATE online_comments SET user_id = 365, comment_author = 'brijesh' WHERE comment_ID = 23;
UPDATE online_users SET display_name = 'Brijesh Desai' WHERE ID = 365;
UPDATE online_comments SET user_id = 1110, comment_author = 'Sanjana Reddy' WHERE comment_ID = 61;
UPDATE online_users SET display_name = 'Sanjana Reddy' WHERE ID = 1110;
UPDATE online_comments SET user_id = 1111, comment_author = 'Karthik Swaminathan' WHERE comment_ID = 62;
UPDATE online_users SET display_name = 'Karthik Swaminathan' WHERE ID = 1111;
UPDATE online_comments SET user_id = 1112, comment_author = 'Lavanya Sundar' WHERE comment_ID = 63;
UPDATE online_users SET display_name = 'Lavanya Sundar' WHERE ID = 1112;
UPDATE online_comments SET user_id = 1113, comment_author = 'Ashwin Prabhu' WHERE comment_ID = 64;
UPDATE online_users SET display_name = 'Ashwin Prabhu' WHERE ID = 1113;
UPDATE online_comments SET user_id = 1114, comment_author = 'Deepa Subramanian' WHERE comment_ID = 65;
UPDATE online_users SET display_name = 'Deepa Subramanian' WHERE ID = 1114;
UPDATE online_comments SET user_id = 1115, comment_author = 'Vignesh Balaji' WHERE comment_ID = 66;
UPDATE online_users SET display_name = 'Vignesh Balaji' WHERE ID = 1115;
UPDATE online_comments SET user_id = 1116, comment_author = 'Keerthi Varma' WHERE comment_ID = 67;
UPDATE online_users SET display_name = 'Keerthi Varma' WHERE ID = 1116;
UPDATE online_comments SET user_id = 1117, comment_author = 'Senthil Kumar' WHERE comment_ID = 68;
UPDATE online_users SET display_name = 'Senthil Kumar' WHERE ID = 1117;
UPDATE online_comments SET user_id = 1118, comment_author = 'Aishwarya Venkat' WHERE comment_ID = 69;
UPDATE online_users SET display_name = 'Aishwarya Venkat' WHERE ID = 1118;
UPDATE online_comments SET user_id = 1119, comment_author = 'Praveen Natarajan' WHERE comment_ID = 70;
UPDATE online_users SET display_name = 'Praveen Natarajan' WHERE ID = 1119;
UPDATE online_comments SET user_id = 1120, comment_author = 'Janani Ramaswamy' WHERE comment_ID = 151;
UPDATE online_users SET display_name = 'Janani Ramaswamy' WHERE ID = 1120;
UPDATE online_comments SET user_id = 1121, comment_author = 'Ganesh Moorthy' WHERE comment_ID = 152;
UPDATE online_users SET display_name = 'Ganesh Moorthy' WHERE ID = 1121;
UPDATE online_comments SET user_id = 1122, comment_author = 'Malini Parthasarathy' WHERE comment_ID = 153;
UPDATE online_users SET display_name = 'Malini Parthasarathy' WHERE ID = 1122;
UPDATE online_comments SET user_id = 1123, comment_author = 'Harish Raghavan' WHERE comment_ID = 154;
UPDATE online_users SET display_name = 'Harish Raghavan' WHERE ID = 1123;
UPDATE online_comments SET user_id = 1124, comment_author = 'Swetha Rajan' WHERE comment_ID = 155;
UPDATE online_users SET display_name = 'Swetha Rajan' WHERE ID = 1124;
UPDATE online_comments SET user_id = 1125, comment_author = 'Murali Krishna' WHERE comment_ID = 156;
UPDATE online_users SET display_name = 'Murali Krishna' WHERE ID = 1125;
UPDATE online_comments SET user_id = 1126, comment_author = 'Nithya Kalyani' WHERE comment_ID = 157;
UPDATE online_users SET display_name = 'Nithya Kalyani' WHERE ID = 1126;
UPDATE online_comments SET user_id = 1127, comment_author = 'Arvind Venkatesh' WHERE comment_ID = 158;
UPDATE online_users SET display_name = 'Arvind Venkatesh' WHERE ID = 1127;
UPDATE online_comments SET user_id = 1128, comment_author = 'Pavithra Shankar' WHERE comment_ID = 159;
UPDATE online_users SET display_name = 'Pavithra Shankar' WHERE ID = 1128;
UPDATE online_comments SET user_id = 1129, comment_author = 'Suresh Babu' WHERE comment_ID = 160;
UPDATE online_users SET display_name = 'Suresh Babu' WHERE ID = 1129;
UPDATE online_comments SET user_id = 1130, comment_author = 'Uma Maheshwari' WHERE comment_ID = 161;
UPDATE online_users SET display_name = 'Uma Maheshwari' WHERE ID = 1130;
UPDATE online_comments SET user_id = 1131, comment_author = 'Vijay Narayanan' WHERE comment_ID = 162;
UPDATE online_users SET display_name = 'Vijay Narayanan' WHERE ID = 1131;
UPDATE online_comments SET user_id = 1132, comment_author = 'Bindu Madhavi' WHERE comment_ID = 163;
UPDATE online_users SET display_name = 'Bindu Madhavi' WHERE ID = 1132;
UPDATE online_comments SET user_id = 1133, comment_author = 'Sandeep Menon' WHERE comment_ID = 164;
UPDATE online_users SET display_name = 'Sandeep Menon' WHERE ID = 1133;
UPDATE online_comments SET user_id = 1134, comment_author = 'Revathi Chandran' WHERE comment_ID = 165;
UPDATE online_users SET display_name = 'Revathi Chandran' WHERE ID = 1134;
UPDATE online_comments SET user_id = 1135, comment_author = 'Deepak Viswanathan' WHERE comment_ID = 166;
UPDATE online_users SET display_name = 'Deepak Viswanathan' WHERE ID = 1135;
UPDATE online_comments SET user_id = 1136, comment_author = 'Sandhya Gopalan' WHERE comment_ID = 167;
UPDATE online_users SET display_name = 'Sandhya Gopalan' WHERE ID = 1136;
UPDATE online_comments SET user_id = 1137, comment_author = 'Madhavan Unni' WHERE comment_ID = 168;
UPDATE online_users SET display_name = 'Madhavan Unni' WHERE ID = 1137;
UPDATE online_comments SET user_id = 1138, comment_author = 'Vidya Srinivasan' WHERE comment_ID = 169;
UPDATE online_users SET display_name = 'Vidya Srinivasan' WHERE ID = 1138;
UPDATE online_comments SET user_id = 1139, comment_author = 'Rameshwaram Iyer' WHERE comment_ID = 170;
UPDATE online_users SET display_name = 'Rameshwaram Iyer' WHERE ID = 1139;
UPDATE online_comments SET user_id = 4, comment_author = 'hardik3253' WHERE comment_ID = 4;
UPDATE online_comments SET user_id = 360, comment_author = 'hardikp' WHERE comment_ID = 28;
UPDATE online_comments SET user_id = 1140, comment_author = 'Jaspreet Singh' WHERE comment_ID = 51;
UPDATE online_users SET display_name = 'Jaspreet Singh' WHERE ID = 1140;
UPDATE online_comments SET user_id = 1141, comment_author = 'Manpreet Kaur' WHERE comment_ID = 52;
UPDATE online_users SET display_name = 'Manpreet Kaur' WHERE ID = 1141;
UPDATE online_comments SET user_id = 1142, comment_author = 'Harpreet Sandhu' WHERE comment_ID = 53;
UPDATE online_users SET display_name = 'Harpreet Sandhu' WHERE ID = 1142;
UPDATE online_comments SET user_id = 1143, comment_author = 'Gurpreet Dhillon' WHERE comment_ID = 54;
UPDATE online_users SET display_name = 'Gurpreet Dhillon' WHERE ID = 1143;
UPDATE online_comments SET user_id = 1144, comment_author = 'Navneet Gill' WHERE comment_ID = 55;
UPDATE online_users SET display_name = 'Navneet Gill' WHERE ID = 1144;
UPDATE online_comments SET user_id = 1145, comment_author = 'Amritpal Brar' WHERE comment_ID = 56;
UPDATE online_users SET display_name = 'Amritpal Brar' WHERE ID = 1145;
UPDATE online_comments SET user_id = 1146, comment_author = 'Simranjit Deol' WHERE comment_ID = 57;
UPDATE online_users SET display_name = 'Simranjit Deol' WHERE ID = 1146;
UPDATE online_comments SET user_id = 1147, comment_author = 'Balwinder Grewal' WHERE comment_ID = 58;
UPDATE online_users SET display_name = 'Balwinder Grewal' WHERE ID = 1147;
UPDATE online_comments SET user_id = 1148, comment_author = 'Ramanpreet Toor' WHERE comment_ID = 59;
UPDATE online_users SET display_name = 'Ramanpreet Toor' WHERE ID = 1148;
UPDATE online_comments SET user_id = 1149, comment_author = 'Daljit Cheema' WHERE comment_ID = 60;
UPDATE online_users SET display_name = 'Daljit Cheema' WHERE ID = 1149;
UPDATE online_comments SET user_id = 1150, comment_author = 'Sukhwinder Virk' WHERE comment_ID = 131;
UPDATE online_users SET display_name = 'Sukhwinder Virk' WHERE ID = 1150;
UPDATE online_comments SET user_id = 1151, comment_author = 'Kirandeep Chahal' WHERE comment_ID = 132;
UPDATE online_users SET display_name = 'Kirandeep Chahal' WHERE ID = 1151;
UPDATE online_comments SET user_id = 1152, comment_author = 'Ravinder Bajwa' WHERE comment_ID = 133;
UPDATE online_users SET display_name = 'Ravinder Bajwa' WHERE ID = 1152;
UPDATE online_comments SET user_id = 1153, comment_author = 'Harleen Sidhu' WHERE comment_ID = 134;
UPDATE online_users SET display_name = 'Harleen Sidhu' WHERE ID = 1153;
UPDATE online_comments SET user_id = 1154, comment_author = 'Paramjit Mann' WHERE comment_ID = 135;
UPDATE online_users SET display_name = 'Paramjit Mann' WHERE ID = 1154;
UPDATE online_comments SET user_id = 1155, comment_author = 'Prabhjot Johal' WHERE comment_ID = 136;
UPDATE online_users SET display_name = 'Prabhjot Johal' WHERE ID = 1155;
UPDATE online_comments SET user_id = 1156, comment_author = 'Mandeep Bains' WHERE comment_ID = 137;
UPDATE online_users SET display_name = 'Mandeep Bains' WHERE ID = 1156;
UPDATE online_comments SET user_id = 1157, comment_author = 'Gurinder Randhawa' WHERE comment_ID = 138;
UPDATE online_users SET display_name = 'Gurinder Randhawa' WHERE ID = 1157;
UPDATE online_comments SET user_id = 1158, comment_author = 'Rajwinder Kahlon' WHERE comment_ID = 139;
UPDATE online_users SET display_name = 'Rajwinder Kahlon' WHERE ID = 1158;
UPDATE online_comments SET user_id = 1159, comment_author = 'Surinder Aulakh' WHERE comment_ID = 140;
UPDATE online_users SET display_name = 'Surinder Aulakh' WHERE ID = 1159;
UPDATE online_comments SET user_id = 1160, comment_author = 'Kamaljit Sohi' WHERE comment_ID = 141;
UPDATE online_users SET display_name = 'Kamaljit Sohi' WHERE ID = 1160;
UPDATE online_comments SET user_id = 1161, comment_author = 'Loveleen Hundal' WHERE comment_ID = 142;
UPDATE online_users SET display_name = 'Loveleen Hundal' WHERE ID = 1161;
UPDATE online_comments SET user_id = 1162, comment_author = 'Satnam Dhaliwal' WHERE comment_ID = 143;
UPDATE online_users SET display_name = 'Satnam Dhaliwal' WHERE ID = 1162;
UPDATE online_comments SET user_id = 1163, comment_author = 'Rupinder Boparai' WHERE comment_ID = 144;
UPDATE online_users SET display_name = 'Rupinder Boparai' WHERE ID = 1163;
UPDATE online_comments SET user_id = 1164, comment_author = 'Hardeep Sekhon' WHERE comment_ID = 145;
UPDATE online_users SET display_name = 'Hardeep Sekhon' WHERE ID = 1164;
UPDATE online_comments SET user_id = 1165, comment_author = 'Maninder Saini' WHERE comment_ID = 146;
UPDATE online_users SET display_name = 'Maninder Saini' WHERE ID = 1165;
UPDATE online_comments SET user_id = 1166, comment_author = 'Puneet Atwal' WHERE comment_ID = 147;
UPDATE online_users SET display_name = 'Puneet Atwal' WHERE ID = 1166;
UPDATE online_comments SET user_id = 1167, comment_author = 'Harinder Thandi' WHERE comment_ID = 148;
UPDATE online_users SET display_name = 'Harinder Thandi' WHERE ID = 1167;
UPDATE online_comments SET user_id = 1168, comment_author = 'Sarabjit Lamba' WHERE comment_ID = 149;
UPDATE online_users SET display_name = 'Sarabjit Lamba' WHERE ID = 1168;
UPDATE online_comments SET user_id = 1169, comment_author = 'Amaninder Garcha' WHERE comment_ID = 150;
UPDATE online_users SET display_name = 'Amaninder Garcha' WHERE ID = 1169;
UPDATE online_comments SET user_id = 4, comment_author = 'hardik3253' WHERE comment_ID = 10;
UPDATE online_comments SET user_id = 10, comment_author = 'hardik123' WHERE comment_ID = 16;
UPDATE online_comments SET user_id = 1170, comment_author = 'Zoya Siddiqui' WHERE comment_ID = 41;
UPDATE online_users SET display_name = 'Zoya Siddiqui' WHERE ID = 1170;
UPDATE online_comments SET user_id = 1171, comment_author = 'Farhan Merchant' WHERE comment_ID = 42;
UPDATE online_users SET display_name = 'Farhan Merchant' WHERE ID = 1171;
UPDATE online_comments SET user_id = 1172, comment_author = 'Sana Qureshi' WHERE comment_ID = 43;
UPDATE online_users SET display_name = 'Sana Qureshi' WHERE ID = 1172;
UPDATE online_comments SET user_id = 1173, comment_author = 'Danish Khan' WHERE comment_ID = 44;
UPDATE online_users SET display_name = 'Danish Khan' WHERE ID = 1173;
UPDATE online_comments SET user_id = 1174, comment_author = 'Afreen Fatima' WHERE comment_ID = 45;
UPDATE online_users SET display_name = 'Afreen Fatima' WHERE ID = 1174;
UPDATE online_comments SET user_id = 1175, comment_author = 'Rehan Ansari' WHERE comment_ID = 46;
UPDATE online_users SET display_name = 'Rehan Ansari' WHERE ID = 1175;
UPDATE online_comments SET user_id = 1176, comment_author = 'Bushra Shaikh' WHERE comment_ID = 47;
UPDATE online_users SET display_name = 'Bushra Shaikh' WHERE ID = 1176;
UPDATE online_comments SET user_id = 1177, comment_author = 'Arbaaz Mirza' WHERE comment_ID = 48;
UPDATE online_users SET display_name = 'Arbaaz Mirza' WHERE ID = 1177;
UPDATE online_comments SET user_id = 1178, comment_author = 'Heena Kausar' WHERE comment_ID = 49;
UPDATE online_users SET display_name = 'Heena Kausar' WHERE ID = 1178;
UPDATE online_comments SET user_id = 1179, comment_author = 'Imran Merchant' WHERE comment_ID = 50;
UPDATE online_users SET display_name = 'Imran Merchant' WHERE ID = 1179;
UPDATE online_comments SET user_id = 1180, comment_author = 'Shabana Parveen' WHERE comment_ID = 111;
UPDATE online_users SET display_name = 'Shabana Parveen' WHERE ID = 1180;
UPDATE online_comments SET user_id = 1181, comment_author = 'Rizwan Ahmed' WHERE comment_ID = 112;
UPDATE online_users SET display_name = 'Rizwan Ahmed' WHERE ID = 1181;
UPDATE online_comments SET user_id = 1182, comment_author = 'Nazia Begum' WHERE comment_ID = 113;
UPDATE online_users SET display_name = 'Nazia Begum' WHERE ID = 1182;
UPDATE online_comments SET user_id = 1183, comment_author = 'Tariq Mansoori' WHERE comment_ID = 114;
UPDATE online_users SET display_name = 'Tariq Mansoori' WHERE ID = 1183;
UPDATE online_comments SET user_id = 1184, comment_author = 'Samina Khatun' WHERE comment_ID = 115;
UPDATE online_users SET display_name = 'Samina Khatun' WHERE ID = 1184;
UPDATE online_comments SET user_id = 1185, comment_author = 'Waseem Sayed' WHERE comment_ID = 116;
UPDATE online_users SET display_name = 'Waseem Sayed' WHERE ID = 1185;
UPDATE online_comments SET user_id = 1186, comment_author = 'Zeenat Kazi' WHERE comment_ID = 117;
UPDATE online_users SET display_name = 'Zeenat Kazi' WHERE ID = 1186;
UPDATE online_comments SET user_id = 1187, comment_author = 'Shahid Memon' WHERE comment_ID = 118;
UPDATE online_users SET display_name = 'Shahid Memon' WHERE ID = 1187;
UPDATE online_comments SET user_id = 1188, comment_author = 'Farida Banu' WHERE comment_ID = 119;
UPDATE online_users SET display_name = 'Farida Banu' WHERE ID = 1188;
UPDATE online_comments SET user_id = 1189, comment_author = 'Naeem Qureshi' WHERE comment_ID = 120;
UPDATE online_users SET display_name = 'Naeem Qureshi' WHERE ID = 1189;
UPDATE online_comments SET user_id = 1190, comment_author = 'Salma Sultana' WHERE comment_ID = 121;
UPDATE online_users SET display_name = 'Salma Sultana' WHERE ID = 1190;
UPDATE online_comments SET user_id = 1191, comment_author = 'Feroz Contractor' WHERE comment_ID = 122;
UPDATE online_users SET display_name = 'Feroz Contractor' WHERE ID = 1191;
UPDATE online_comments SET user_id = 1192, comment_author = 'Parveen Khan' WHERE comment_ID = 123;
UPDATE online_users SET display_name = 'Parveen Khan' WHERE ID = 1192;
UPDATE online_comments SET user_id = 1193, comment_author = 'Aslam Sheikh' WHERE comment_ID = 124;
UPDATE online_users SET display_name = 'Aslam Sheikh' WHERE ID = 1193;
UPDATE online_comments SET user_id = 1194, comment_author = 'Yasmin Morani' WHERE comment_ID = 125;
UPDATE online_users SET display_name = 'Yasmin Morani' WHERE ID = 1194;
UPDATE online_comments SET user_id = 1195, comment_author = 'Tanveer Warsi' WHERE comment_ID = 126;
UPDATE online_users SET display_name = 'Tanveer Warsi' WHERE ID = 1195;
UPDATE online_comments SET user_id = 1196, comment_author = 'Rukhsar Rehman' WHERE comment_ID = 127;
UPDATE online_users SET display_name = 'Rukhsar Rehman' WHERE ID = 1196;
UPDATE online_comments SET user_id = 1197, comment_author = 'Nadeem Jafri' WHERE comment_ID = 128;
UPDATE online_users SET display_name = 'Nadeem Jafri' WHERE ID = 1197;
UPDATE online_comments SET user_id = 1198, comment_author = 'Mehrunissa Khan' WHERE comment_ID = 129;
UPDATE online_users SET display_name = 'Mehrunissa Khan' WHERE ID = 1198;
UPDATE online_comments SET user_id = 1199, comment_author = 'Sajid Patel' WHERE comment_ID = 130;
UPDATE online_users SET display_name = 'Sajid Patel' WHERE ID = 1199;
UPDATE online_comments SET user_id = 1200, comment_author = 'Chirag Thakkar' WHERE comment_ID = 31;
UPDATE online_users SET display_name = 'Chirag Thakkar' WHERE ID = 1200;
UPDATE online_comments SET user_id = 1201, comment_author = 'Kinjal Mehta' WHERE comment_ID = 32;
UPDATE online_users SET display_name = 'Kinjal Mehta' WHERE ID = 1201;
UPDATE online_comments SET user_id = 1202, comment_author = 'Parth Vora' WHERE comment_ID = 33;
UPDATE online_users SET display_name = 'Parth Vora' WHERE ID = 1202;
UPDATE online_comments SET user_id = 1203, comment_author = 'Drashti Desai' WHERE comment_ID = 34;
UPDATE online_users SET display_name = 'Drashti Desai' WHERE ID = 1203;
UPDATE online_comments SET user_id = 1204, comment_author = 'Bhavin Shah' WHERE comment_ID = 35;
UPDATE online_users SET display_name = 'Bhavin Shah' WHERE ID = 1204;
UPDATE online_comments SET user_id = 1205, comment_author = 'Urvashi Panchal' WHERE comment_ID = 36;
UPDATE online_users SET display_name = 'Urvashi Panchal' WHERE ID = 1205;
UPDATE online_comments SET user_id = 1206, comment_author = 'Harshil Trivedi' WHERE comment_ID = 37;
UPDATE online_users SET display_name = 'Harshil Trivedi' WHERE ID = 1206;
UPDATE online_comments SET user_id = 1207, comment_author = 'Riddhi Dave' WHERE comment_ID = 38;
UPDATE online_users SET display_name = 'Riddhi Dave' WHERE ID = 1207;
UPDATE online_comments SET user_id = 1208, comment_author = 'Maulik Pandya' WHERE comment_ID = 39;
UPDATE online_users SET display_name = 'Maulik Pandya' WHERE ID = 1208;
UPDATE online_comments SET user_id = 1209, comment_author = 'Falguni Sheth' WHERE comment_ID = 40;
UPDATE online_users SET display_name = 'Falguni Sheth' WHERE ID = 1209;
UPDATE online_comments SET user_id = 1210, comment_author = 'Jignesh Solanki' WHERE comment_ID = 91;
UPDATE online_users SET display_name = 'Jignesh Solanki' WHERE ID = 1210;
UPDATE online_comments SET user_id = 1211, comment_author = 'Jagruti Patel' WHERE comment_ID = 92;
UPDATE online_users SET display_name = 'Jagruti Patel' WHERE ID = 1211;
UPDATE online_comments SET user_id = 1212, comment_author = 'Dharmesh Ruparel' WHERE comment_ID = 93;
UPDATE online_users SET display_name = 'Dharmesh Ruparel' WHERE ID = 1212;
UPDATE online_comments SET user_id = 1213, comment_author = 'Maitri Joshi' WHERE comment_ID = 94;
UPDATE online_users SET display_name = 'Maitri Joshi' WHERE ID = 1213;
UPDATE online_comments SET user_id = 1214, comment_author = 'Kaushik Shukla' WHERE comment_ID = 95;
UPDATE online_users SET display_name = 'Kaushik Shukla' WHERE ID = 1214;
UPDATE online_comments SET user_id = 1215, comment_author = 'Forum Bhatt' WHERE comment_ID = 96;
UPDATE online_users SET display_name = 'Forum Bhatt' WHERE ID = 1215;
UPDATE online_comments SET user_id = 1216, comment_author = 'Dhaval Kothari' WHERE comment_ID = 97;
UPDATE online_users SET display_name = 'Dhaval Kothari' WHERE ID = 1216;
UPDATE online_comments SET user_id = 1217, comment_author = 'Vaishali Parikh' WHERE comment_ID = 98;
UPDATE online_users SET display_name = 'Vaishali Parikh' WHERE ID = 1217;
UPDATE online_comments SET user_id = 1218, comment_author = 'Hiren Sanghavi' WHERE comment_ID = 99;
UPDATE online_users SET display_name = 'Hiren Sanghavi' WHERE ID = 1218;
UPDATE online_comments SET user_id = 1219, comment_author = 'Tejal Gada' WHERE comment_ID = 100;
UPDATE online_users SET display_name = 'Tejal Gada' WHERE ID = 1219;
UPDATE online_comments SET user_id = 1220, comment_author = 'Kalpesh Modi' WHERE comment_ID = 101;
UPDATE online_users SET display_name = 'Kalpesh Modi' WHERE ID = 1220;
UPDATE online_comments SET user_id = 1221, comment_author = 'Mansi Sompura' WHERE comment_ID = 102;
UPDATE online_users SET display_name = 'Mansi Sompura' WHERE ID = 1221;
UPDATE online_comments SET user_id = 1222, comment_author = 'Bhargav Raval' WHERE comment_ID = 103;
UPDATE online_users SET display_name = 'Bhargav Raval' WHERE ID = 1222;
UPDATE online_comments SET user_id = 1223, comment_author = 'Kruti Dholakia' WHERE comment_ID = 104;
UPDATE online_users SET display_name = 'Kruti Dholakia' WHERE ID = 1223;
UPDATE online_comments SET user_id = 1224, comment_author = 'Mehul Choksi' WHERE comment_ID = 105;
UPDATE online_users SET display_name = 'Mehul Choksi' WHERE ID = 1224;
UPDATE online_comments SET user_id = 1225, comment_author = 'Payal Chandarana' WHERE comment_ID = 106;
UPDATE online_users SET display_name = 'Payal Chandarana' WHERE ID = 1225;
UPDATE online_comments SET user_id = 1226, comment_author = 'Chetan Barot' WHERE comment_ID = 107;
UPDATE online_users SET display_name = 'Chetan Barot' WHERE ID = 1226;
UPDATE online_comments SET user_id = 1227, comment_author = 'Toral Maniar' WHERE comment_ID = 108;
UPDATE online_users SET display_name = 'Toral Maniar' WHERE ID = 1227;
UPDATE online_comments SET user_id = 1228, comment_author = 'Pratik Lakhani' WHERE comment_ID = 109;
UPDATE online_users SET display_name = 'Pratik Lakhani' WHERE ID = 1228;
UPDATE online_comments SET user_id = 1229, comment_author = 'Nidhi Oza' WHERE comment_ID = 110;
UPDATE online_users SET display_name = 'Nidhi Oza' WHERE ID = 1229;
UPDATE online_comments SET user_id = 392, comment_author = 'ajith' WHERE comment_ID = 213;
UPDATE online_users SET display_name = 'AJITH A' WHERE ID = 392;
